sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - COMPOSER_ARGUMENTS=--prefer-lowest
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
    - php: 7.0
      env:
        - EXECUTE_CS_CHECK=true
    - php: hhvm

before_install:
  - echo "extension=ldap.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - travis_retry composer self-update
  - if [[ $SYMFONY_VERSION != '' ]]; then travis_retry composer require --dev --no-update symfony/symfony:${SYMFONY_VERSION} ; fi
  - if [[ $EXECUTE_CS_CHECK != 'true' ]]; then travis_retry composer remove --dev --no-update fabpot/php-cs-fixer ; fi
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then travis_retry composer require --dev --no-update satooshi/php-coveralls:^1.0.0 ; fi

install:
  - travis_retry composer update --no-interaction $COMPOSER_ARGUMENTS
  - composer info -i

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then vendor/bin/php-cs-fixer fix -v --dry-run; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then travis_retry ./vendor/bin/coveralls -v; fi
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then travis_retry wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then travis_retry php ocular.phar code-coverage:upload --format=php-clover clover.xml ; fi
